-- Fase 3 - Base editavel de regras da casa
-- Data: 2026-04-04
-- Objetivo:
-- 1) Criar a tabela assistant_rules
-- 2) Inserir regras operacionais iniciais editaveis
-- 3) Permitir que a Aura consulte regras sem hardcode no prompt

begin;

create table if not exists public.assistant_rules (
  id bigint generated by default as identity primary key,
  category text not null,
  rule_key text not null,
  value text not null,
  active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint assistant_rules_unique_key unique (category, rule_key)
);

insert into public.assistant_rules (category, rule_key, value, active, notes)
values
  ('wifi', 'wifi_name', 'Nao cadastrado', true, 'Atualize com o nome real da rede Wi-Fi do hotel.'),
  ('wifi', 'wifi_password', 'Nao cadastrada', true, 'Atualize com a senha real do Wi-Fi quando quiser liberar resposta automatica.'),
  ('checkin_checkout', 'checkin_time', 'Check-in a partir das 14h.', true, 'Horario padrao de entrada.'),
  ('checkin_checkout', 'checkout_time', 'Check-out ate 12h.', true, 'Horario padrao de saida.'),
  ('pets', 'pet_policy', 'Aceitamos pets de ate 12kg apenas em Chales/Anexos, cerca de 70m da ala principal.', true, 'Politica inicial trazida do material operacional atual.'),
  ('menu', 'breakfast_hours', 'Cafe da manha das 08:30 as 10:30.', true, 'Horario atual do cafe da manha.'),
  ('internal_policies', 'house_rules_summary', 'Caso a regra especifica nao esteja cadastrada, a Aura deve informar que a equipe precisa atualizar a base interna e evitar inventar informacoes.', true, 'Regra de seguranca para evitar alucinacao.')
on conflict (category, rule_key) do nothing;

create or replace function public.set_assistant_rules_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_assistant_rules_updated_at on public.assistant_rules;

create trigger set_assistant_rules_updated_at
before update on public.assistant_rules
for each row
execute function public.set_assistant_rules_updated_at();

commit;
