create extension if not exists pgcrypto;

create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  message_template text not null,
  selected_label_ids jsonb not null default '[]'::jsonb,
  selected_label_names jsonb not null default '[]'::jsonb,
  base_count integer not null default 0,
  duplicate_count integer not null default 0,
  invalid_count integer not null default 0,
  audience_count integer not null default 0,
  sent_count integer not null default 0,
  replied_count integer not null default 0,
  ignored_count integer not null default 0,
  blocked_count integer not null default 0,
  failed_count integer not null default 0,
  status text not null default 'draft',
  created_by text null,
  created_at timestamptz not null default now(),
  started_at timestamptz null,
  finished_at timestamptz null,
  constraint campaigns_status_check check (
    status in ('draft', 'sending', 'completed', 'completed_with_failures')
  )
);

create table if not exists public.campaign_recipients (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  lead_record_id bigint null,
  lead_name text null,
  phone_number text not null,
  personalized_message text null,
  delivery_status text not null default 'pending',
  error_message text null,
  sent_at timestamptz null,
  replied_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campaign_recipients_status_check check (
    delivery_status in ('pending', 'sent', 'replied', 'ignored', 'failed', 'blocked')
  )
);

create index if not exists idx_campaigns_created_at on public.campaigns(created_at desc);
create index if not exists idx_campaign_recipients_campaign_id on public.campaign_recipients(campaign_id);
create index if not exists idx_campaign_recipients_phone_number on public.campaign_recipients(phone_number);
create index if not exists idx_campaign_recipients_status on public.campaign_recipients(delivery_status);

create or replace function public.set_campaign_recipient_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_campaign_recipient_updated_at on public.campaign_recipients;

create trigger trg_campaign_recipient_updated_at
before update on public.campaign_recipients
for each row
execute function public.set_campaign_recipient_updated_at();
