-- Fase 4 - Tabela de tarifas anuais
-- Data: 2026-04-04
-- Objetivo:
-- 1) Criar a tabela room_rates
-- 2) Inserir tarifas iniciais editaveis
-- 3) Permitir que a Aura consulte tarifas sem hardcode no prompt

begin;

create table if not exists public.room_rates (
  id bigint generated by default as identity primary key,
  room_type text not null,
  season_name text not null,
  date_from date not null,
  date_to date not null,
  days_of_week smallint[] not null default array[0,1,2,3,4,5,6],
  base_price numeric(10,2) not null,
  min_nights integer not null default 1,
  priority integer not null default 100,
  extra_adult_price numeric(10,2) not null default 0,
  child_price_6_11 numeric(10,2) not null default 0,
  child_price_0_5 numeric(10,2) not null default 0,
  active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint room_rates_positive_price check (base_price >= 0),
  constraint room_rates_positive_min_nights check (min_nights >= 1),
  constraint room_rates_valid_period check (date_to >= date_from)
);

insert into public.room_rates (
  room_type,
  season_name,
  date_from,
  date_to,
  days_of_week,
  base_price,
  min_nights,
  priority,
  extra_adult_price,
  child_price_6_11,
  child_price_0_5,
  active,
  notes
)
values
  ('Chale/Anexo', 'Tarifa regular - Domingo a Sexta', '2026-01-01', '2026-12-31', array[0,1,2,3,4,5], 349, 1, 100, 100, 80, 0, true, 'Base trazida do workflow legado.'),
  ('Apto Terreo', 'Tarifa regular - Domingo a Sexta', '2026-01-01', '2026-12-31', array[0,1,2,3,4,5], 359, 1, 100, 100, 80, 0, true, 'Base trazida do workflow legado.'),
  ('Apto Superior', 'Tarifa regular - Domingo a Sexta', '2026-01-01', '2026-12-31', array[0,1,2,3,4,5], 369, 1, 100, 100, 80, 0, true, 'Base trazida do workflow legado.'),
  ('Chale/Anexo', 'Tarifa regular - Sabado', '2026-01-01', '2026-12-31', array[6], 379, 1, 90, 100, 80, 0, true, 'Base trazida do workflow legado.'),
  ('Apto Terreo', 'Tarifa regular - Sabado', '2026-01-01', '2026-12-31', array[6], 389, 1, 90, 100, 80, 0, true, 'Base trazida do workflow legado.'),
  ('Apto Superior', 'Tarifa regular - Sabado', '2026-01-01', '2026-12-31', array[6], 399, 1, 90, 100, 80, 0, true, 'Base trazida do workflow legado.'),
  ('Chale/Anexo', 'Pascoa 2026', '2026-04-03', '2026-04-05', array[0,1,2,3,4,5,6], 599, 3, 10, 100, 80, 0, true, 'Minimo de diarias obrigatorio. Ajuste se necessario.'),
  ('Apto Terreo', 'Pascoa 2026', '2026-04-03', '2026-04-05', array[0,1,2,3,4,5,6], 699, 3, 10, 100, 80, 0, true, 'Minimo de diarias obrigatorio. Ajuste se necessario.'),
  ('Apto Superior', 'Pascoa 2026', '2026-04-03', '2026-04-05', array[0,1,2,3,4,5,6], 799, 3, 10, 100, 80, 0, true, 'Minimo de diarias obrigatorio. Ajuste se necessario.'),
  ('Chale/Anexo', 'Corpus Christi 2026', '2026-06-04', '2026-06-07', array[0,1,2,3,4,5,6], 599, 3, 10, 100, 80, 0, true, 'Minimo de diarias obrigatorio. Ajuste se necessario.'),
  ('Apto Terreo', 'Corpus Christi 2026', '2026-06-04', '2026-06-07', array[0,1,2,3,4,5,6], 699, 3, 10, 100, 80, 0, true, 'Minimo de diarias obrigatorio. Ajuste se necessario.'),
  ('Apto Superior', 'Corpus Christi 2026', '2026-06-04', '2026-06-07', array[0,1,2,3,4,5,6], 799, 3, 10, 100, 80, 0, true, 'Minimo de diarias obrigatorio. Ajuste se necessario.')
on conflict do nothing;

create or replace function public.set_room_rates_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_room_rates_updated_at on public.room_rates;

create trigger set_room_rates_updated_at
before update on public.room_rates
for each row
execute function public.set_room_rates_updated_at();

commit;
